feat: rework socket
lenra-io/lenra_ui_runner pull request #189
Opened 2022-10-13 14:51 UTC by Nesqwik

#182

## Checklist
- [ ] I didn't over-scope my PR
- [ ] My PR title matches the [commit convention](https://www.conventionalcommits.org/en/v1.0.0/)
- [ ] I did not include breaking changes
- [ ] I included unit tests that cover my changes
- [ ] I added/updated the documentation about my changes
- [ ] I made my own code-review before requesting one

## Description of the changes
Fast change to make it work.
We will need a big refactoring on the client/lenra_ui_runner to create the view system for lenra too.
But for now it work like before with the json view.
https://github.com/lenra-io/application-runner/pull/242

2022-10-13 15:05 UTC, Nesqwik commented
@jonas-martinez i have an issue with the `lenra_image_test.dart` file during analyze/test locally. 
No idea why, i did not touch this...

It's working with the CI tho.

Any idea ?

2022-10-14 16:14 UTC, jonas-martinez commented
@Nesqwik Sorry I did not see your message.

Yes you have this issue because you need to run this command to generate the mock files :
`flutter pub run build_runner build`

This is indicated in the README but it might be better to execute it automatically when running the tests. What do you think ?

2022-10-17 13:24 UTC, Nesqwik commented
> This is indicated in the README but it might be better to execute it automatically when running the tests. What do you think ?

Could be yes. We can create a new issue to do this !

2022-10-19 10:06 UTC, pichoemr requested changes

2022-10-19 10:06 UTC, pichoemr commented on lib/models/app_socket_model.dart
> +      {"token": accessToken, "app": appName},
Give the context with the ContextModel

2022-10-19 11:07 UTC, Nesqwik commented on lib/models/app_socket_model.dart
> +      {"token": accessToken, "app": appName},
I don't think it's a good idea to do this here sadly...

The params in the socket connexion are query params. They are encoded in the URL.
If the context is too big we will reach the limit and it won't work anymore.

We should probably create a side channel to handle the context for now.

2022-10-19 11:22 UTC, pichoemr commented on lib/models/app_socket_model.dart
> +      {"token": accessToken, "app": appName},
With the redesign of the application_runner, the context is obtained from the socket settings, you are right, I didn't think of the limit.

I think you can do it in the application_runner PR if the work is not too big, to avoid that the context is not available anymore while the new pr is done.

2022-10-19 11:35 UTC, Nesqwik commented on lib/models/app_socket_model.dart
> +      {"token": accessToken, "app": appName},
The context is not (and never have been) dynamic. That means if the context change, the UI does not rerender.
In my opinion it is a bit pointless to add the context back until we've fond a solution to make the context dynamic.

This will need a lot more work than just adding one channel.

2022-10-24 13:08 UTC, pichoemr approved these changes

2022-11-01 13:00 UTC, merged

2022-11-01 13:01 UTC, shiipou commented
:tada: This PR is included in version 1.0.0-beta.93 :tada:

The release is available on [GitHub release](https://github.com/lenra-io/lenra_ui_runner/releases/tag/v1.0.0-beta.93)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket:

2023-02-27 15:17 UTC, shiipou commented
:tada: This PR is included in version 1.0.0-alpha.1 :tada:

The release is available on [GitHub release](https://github.com/lenra-io/lenra_ui_runner/releases/tag/v1.0.0-alpha.1)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: