feat: receive response from listeners
lenra-io/lenra_ui_runner pull request #191
Opened 2022-10-18 08:54 UTC by pichoemr

linked to https://github.com/lenra-io/application-runner/issues/247

## Checklist
- [ ] I didn't over-scope my PR
- [ ] My PR title matches the [commit convention](https://www.conventionalcommits.org/en/v1.0.0/)
- [ ] I did not include breaking changes
- [ ] I included unit tests that cover my changes
- [ ] I added/updated the documentation about my changes
- [ ] I made my own code-review before requesting one

## Description of the changes

remove notifier and call a callback when push receive response

2022-10-18 09:28 UTC, jonas-martinez approved these changes

2022-10-18 09:29 UTC, jonas-martinez requested changes
Most of the tests are broken

I can take care of it if you want

2022-10-18 12:37 UTC, taorepoara approved these changes
Seems OK

2022-10-18 12:43 UTC, taorepoara commented
You should fix the showcase example

2022-10-18 14:14 UTC, Nesqwik requested changes

2022-10-18 14:14 UTC, Nesqwik commented on lib/models/channel_model.dart
> +  void sendEvent(Event notification, Function(Map<dynamic, dynamic>) callback) {
could you change this function to return a future rather than a callback ? 
It is probably more convenient to use

2022-10-18 14:14 UTC, Nesqwik commented on lib/models/channel_model.dart
> +  void sendEvent(Event notification, Function(Map<dynamic, dynamic>) callback) {
Note: Use [Completer](https://api.dart.dev/stable/2.10.5/dart-async/Completer-class.html) to create a new future and add the receive("error") to handle the error response

2022-10-18 17:17 UTC, Nesqwik requested changes

2022-10-18 17:17 UTC, Nesqwik commented on lib/models/channel_model.dart
> +    channel!.send('run', notification.toMap())!.receive("ok", (response) => completer.complete(response));
the `.receive("error", (error) => completer.completeError(error))` is missing to handle the error return

2022-10-19 09:41 UTC, jonas-martinez requested changes
This is some really good job ! Everything looks good to me.

Can you just fix the CI and add the proposed changes in nesqwik review ?

2022-10-19 10:41 UTC, Nesqwik requested changes
One small change, fix the CI and we can merge this one :)

2022-10-19 10:41 UTC, Nesqwik commented on lib/models/channel_model.dart
> +        .receive("error", (error) => completer.complete(error));
For the error, the completer should be completeError if i'm not mistaken
see : https://api.dart.dev/stable/2.10.5/dart-async/Completer/completeError.html

```suggestion
        .receive("error", (error) => completer.completeError(error));
```

2022-10-21 10:59 UTC, jonas-martinez approved these changes

2022-10-21 11:00 UTC, merged

2022-10-21 11:00 UTC, shiipou commented
:tada: This PR is included in version 1.0.0-beta.91 :tada:

The release is available on [GitHub release](https://github.com/lenra-io/lenra_ui_runner/releases/tag/v1.0.0-beta.91)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket:

2023-02-27 15:17 UTC, shiipou commented
:tada: This PR is included in version 1.0.0-alpha.1 :tada:

The release is available on [GitHub release](https://github.com/lenra-io/lenra_ui_runner/releases/tag/v1.0.0-alpha.1)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: